const SCOPE = 'test2/';

export const CREATE_TAXONOMY_NODE = `${SCOPE}CREATE_TAXONOMY_NODE`;
export const SUCCESS_CREATE_TAXONOMY_NODE = `${SCOPE}SUCCESS_CREATE_TAXONOMY_NODE`;
export const FAILED_CREATE_TAXONOMY_NODE = `${SCOPE}FAILED_CREATE_TAXONOMY_NODE`;
