export const LOAD_IBIS_RESPONSE = 'ibis/LOAD_IBIS_RESPONSE';
export const LOAD_IBIS_RESPONSE_SUCCESS = 'ibis/LOAD_IBIS_RESPONSE_SUCCESS';
export const LOAD_IBIS_RESPONSE_ERROR = 'ibis/LOAD_IBIS_RESPONSE_ERROR';
