const SCOPE = 'public/Auth/';

export const DEFAULT_ACTION = `${SCOPE}DEFAULT_ACTION`;

export const LOGIN = `${SCOPE}LOGIN`;
export const LOGIN_FAILED = `${SCOPE}LOGIN_FAILED`;
export const LOGIN_SUCCESS = `${SCOPE}LOGIN_SUCCESS`;

export const LOGOUT = `${SCOPE}LOGOUT`;
export const LOGOUT_FAILED = `${SCOPE}LOGOUT_FAILED`;
export const LOGOUT_SUCCESS = `${SCOPE}LOGOUT_SUCCESS`;

export const GET_USER_METADATA = `${SCOPE}GET_USER_METADATA`;
export const GET_USER_METADATA_SUCCESS = `${SCOPE}GET_USER_METADATA_SUCCESS`;
export const GET_USER_METADATA_FAILED = `${SCOPE}GET_USER_METADATA_FAILED`;

export const FETCH_AUTH0_TOKEN = `${SCOPE}FETCH_AUTH0_TOKEN`;
